version: "3"

services:
  frontend:
    build: ./mangopot_frontend
    command: ["npm", "start"]
    ports:
      - 8081:8081
    networks:
      - app-tier
    volumes:
      - ./mangopot_frontend:/app

  backend:
    build: ./mangopot_backend
    ports:
      - 8080:8080
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
